tiles.setCurrentTilemap(tilemap`level1`)
scene.setBackgroundImage(assets.image`tile map background`)
scene.setBackgroundColor(9)
let mySprite = sprites.create(img`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .....f..........
    .....f..........
    .....f..........
    .....fffffffff..
    ....f3333ff33f..
    ...f33333ff33f..
    ...f333333333f..
    ..fff3333fffff..
    .....f333f......
    .....f333f......
    .....f333f......
    ..fffffffffff...
    .f33f33333f33f..
    f33ff33333ff33f.
    .ff.f33333f.ff..
    ....fffffff.....
    .....33f33......
    .....33f33......
    .....33f33......
    .....33f33......
    ....fffffff.....
    ....f33333f.....
    ...fffffffff....
    `, SpriteKind.Player)
